import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:smart_accounting_mobile/data/ai_health.dart';
import 'package:smart_accounting_mobile/data/snapshot_model.dart';

/// Parity: mobile health formulas must reproduce the desktop engine outputs
/// (modules/ai_platform.py) byte-for-byte — expected values come from
/// health_expected.json generated by tools/gen_mobile_fixtures.py.
void main() {
  late SnapshotData snap;
  late Map<String, dynamic> expected;

  setUpAll(() {
    final plain = File('test/fixtures/demo_snapshot_plain.json')
        .readAsStringSync();
    final wrapper = jsonDecode(plain) as Map<String, dynamic>;
    final payload = jsonDecode(wrapper['data'] as String) as Map<String, dynamic>;
    snap = SnapshotData.fromPayload(payload);
    expected = jsonDecode(
        File('test/fixtures/health_expected.json').readAsStringSync())
        as Map<String, dynamic>;
  });

  test('total score matches desktop engine', () {
    final health = computeHealth(snap);
    final expectedTotal = (expected['health']['total'] as num).toDouble();
    expect(health.total, closeTo(expectedTotal, 0.05));
  });

  test('grade matches desktop engine', () {
    final health = computeHealth(snap);
    expect(health.grade, expected['health']['grade'][0]);
  });

  test('breakdown matches desktop engine (6 dims)', () {
    final health = computeHealth(snap);
    final expectedBreakdown = (expected['health']['breakdown'])
        as Map<String, dynamic>;
    for (final entry in expectedBreakdown.entries) {
      final expectedValue = (entry.value as num).toDouble();
      expect(
        health.breakdown[entry.key],
        closeTo(expectedValue, 0.05),
        reason: 'dim ${entry.key}',
      );
    }
  });

  test('risk radar matches desktop engine (6 axes)', () {
    final health = computeHealth(snap);
    final expectedRadar = expected['radar'] as Map<String, dynamic>;
    for (final entry in expectedRadar.entries) {
      final expectedValue = (entry.value as num).toDouble();
      expect(
        health.riskRadar[entry.key],
        closeTo(expectedValue, 0.05),
        reason: 'risk ${entry.key}',
      );
    }
  });

  test('empty snapshot matches desktop engine defaults', () {
    // Desktop parity: leverage defaults to its full 15 points when
    // debt ratios are absent (0 debts), so the empty total is 15, grade E.
    final empty = SnapshotData(
      companyName: '',
      financialData: const {},
      ratios: const {},
    );
    final health = computeHealth(empty);
    expect(health.total, 15);
    expect(health.grade, 'E');
  });

  test('grade bands follow the total (A/B/E)', () {
    SnapshotData make(Map<String, double> ratios) => SnapshotData(
          companyName: '',
          financialData: const {},
          ratios: ratios,
        );
    // Strong: profitability 30 + liquidity 20 + leverage 14.4 + efficiency 15
    // + stability 10 = ~89 → A
    expect(
        computeHealth(make(const {
          'roe': 40, 'net_profit_margin': 30,
          'current_ratio': 3, 'quick_ratio': 2,
          'inventory_turnover': 12, 'receivables_turnover': 12,
          'z_score': 4, 'debt_to_equity': 0.1, 'debt_ratio': 0.05,
        })).grade,
        'A');
    // Moderate: ~60-79 → B
    expect(
        computeHealth(make(const {
          'roe': 25, 'net_profit_margin': 15,
          'current_ratio': 2.5, 'quick_ratio': 1.5,
          'inventory_turnover': 8, 'receivables_turnover': 8,
          'z_score': 3.2, 'debt_to_equity': 1, 'debt_ratio': 0.4,
        })).grade,
        'B');
    // Empty → E
    expect(computeHealth(make(const {})).grade, 'E');
  });
}
