import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:smart_accounting_mobile/data/ai_health.dart';
import 'package:smart_accounting_mobile/data/ai_summary.dart';
import 'package:smart_accounting_mobile/data/snapshot_model.dart';

/// Parity: the mobile executive summary + recommendations must match the
/// desktop engine (modules/ai_platform.py) — expected Arabic strings come
/// from health_expected.json generated by tools/gen_mobile_fixtures.py.
void main() {
  late SnapshotData snap;
  late Map<String, dynamic> expected;

  setUpAll(() {
    final plain = File('test/fixtures/demo_snapshot_plain.json')
        .readAsStringSync();
    final wrapper = jsonDecode(plain) as Map<String, dynamic>;
    final payload =
        jsonDecode(wrapper['data'] as String) as Map<String, dynamic>;
    snap = SnapshotData.fromPayload(payload);
    expected = jsonDecode(File('test/fixtures/health_expected.json')
        .readAsStringSync()) as Map<String, dynamic>;
  });

  test('executive summary (ar) matches desktop engine string-for-string',
      () {
    final health = computeHealth(snap);
    final summary = executiveSummary(snap, health, 'ar');
    final expectedSummary = (expected['summary'] as List).cast<String>();
    expect(summary.length, expectedSummary.length);
    for (var i = 0; i < expectedSummary.length; i++) {
      expect(summary[i], expectedSummary[i], reason: 'point $i');
    }
  });

  test('recommendations match desktop engine (priority + ar action)', () {
    final recs = strategicRecommendations(snap);
    final expectedRecs =
        (expected['recommendations'] as List).cast<Map<String, dynamic>>();
    expect(recs.length, expectedRecs.length);
    for (var i = 0; i < expectedRecs.length; i++) {
      expect(recs[i].priority, expectedRecs[i]['priority'], reason: 'rec $i');
      // The screen renders actions via I18n; verify the Arabic rendering.
      expect(
        renderAction(recs[i], 'ar'),
        expectedRecs[i]['action'],
        reason: 'rec $i action',
      );
      expect(
        renderImpact(recs[i], 'ar'),
        expectedRecs[i]['impact'],
        reason: 'rec $i impact',
      );
    }
  });

  test('summary for en/fr renders translated text', () {
    final health = computeHealth(snap);
    final en = executiveSummary(snap, health, 'en');
    expect(en.first, contains('Financial health score'));
    final fr = executiveSummary(snap, health, 'fr');
    expect(fr.first, contains('santé'));
  });

  test('empty snapshot summary still lists the health line', () {
    final empty = SnapshotData(
      companyName: '',
      financialData: const {},
      ratios: const {},
    );
    final health = computeHealth(empty);
    final summary = executiveSummary(empty, health, 'ar');
    expect(summary, isNotEmpty);
    expect(summary.first, contains('درجة الصحة المالية'));
  });
}
