# سجل الشاشات المركزي
# ====================
# المصدر الوحيد لقائمة الشاشات (معرّف، اسم، وحدة، فئة) — يستخدمه
# MainWindow لبناء المصانع + حوار توزيع الشاشات لعرض القائمة.

VIEW_REGISTRY = {
    1: ("data_entry", "ui.views.data_entry", "DataEntryView"),
    2: ("dashboard", "ui.views.dashboard", "DashboardView"),
    3: ("ratios", "ui.views.ratios_view", "RatiosView"),
    4: ("dupont", "ui.views.analysis_view", "DuPontView"),
    5: ("audit", "ui.views.audit_view", "AuditView"),
    6: ("reports", "ui.views.reports_view", "ReportsView"),
    7: ("settings", "ui.views.settings_view", "SettingsView"),
    8: ("chat", "ui.views.chat_view", "ChatView"),
    9: ("tax", "ui.views.tax_view", "TaxView"),
    10: ("comparative", "ui.views.comparative_view", "ComparativeView"),
    11: ("cashflow", "ui.views.cashflow_view", "CashFlowView"),
    12: ("security", "ui.views.security_view", "SecurityView"),
    13: ("zscore", "ui.views.zscore_view", "ZScoreView"),
    14: ("forecast", "ui.views.forecasting_view", "ForecastingView"),
    15: ("budget", "ui.views.budget_view", "BudgetView"),
    16: ("cost_center", "ui.views.cost_center_view", "CostCenterView"),
    17: ("breakeven", "ui.views.breakeven_view", "BreakEvenView"),
    18: ("benchmarks", "ui.views.benchmarks_view", "BenchmarkView"),
    19: ("tax_calendar", "ui.views.tax_calendar_view", "TaxCalendarView"),
    20: ("data_import", "ui.views.data_import_view", "DataImportView"),
    21: ("bank_sync", "ui.views.bank_sync_view", "BankSyncView"),
    22: ("scenarios", "ui.views.scenarios_view", "ScenariosView"),
    23: ("advanced_dashboard", "ui.views.advanced_dashboard_view", "AdvancedDashboardView"),
    24: ("ai_insights", "ui.views.ai_insights_view", "AIInsightsView"),
    25: ("cost_profit", "ui.views.cost_center_profitability_view", "CostCenterProfitabilityView"),
    26: ("currency", "ui.views.currency_view", "CurrencyView"),
    27: ("cloud_sync", "ui.views.cloud_sync_view", "CloudSyncView"),
    28: ("demo_data", "ui.views.demo_data_view", "DemoDataView"),
    29: ("user_testing", "ui.views.user_testing_view", "UserTestingView"),
    30: ("ledger", "ui.views.ledger_view", "LedgerView"),
    31: ("partners", "ui.views.partners_view", "PartnersView"),
    32: ("invoicing", "ui.views.invoicing_view", "InvoicingView"),
    33: ("inventory", "ui.views.inventory_view", "InventoryView"),
    34: ("payroll", "ui.views.payroll_view", "PayrollView"),
    35: ("budgeting", "ui.views.budgeting_view", "BudgetingView"),
    36: ("procurement", "ui.views.procurement_view", "ProcurementView"),
    37: ("einvoicing", "ui.views.einvoicing_view", "EInvoicingView"),
    38: ("ias", "ui.views.ias_reports_view", "IASReportsView"),
    39: ("ai_platform", "ui.views.ai_platform_view", "AIPlatformView"),
}
